# Generated by Django 2.2.24 on 2022-07-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '7128_resource_instance_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='sortorder',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
