# Generated by Django 2.2.24 on 2022-08-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '7129_maplayer_sortorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='layersortorder',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
