# Generated by Django 2.2.24 on 2022-10-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '7130_node_layersortorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maplayer',
            old_name='sortorder',
            new_name='layersortorder',
        ),
    ]
