# Generated by Django 3.2.18 on 2023-03-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '8770_bulk_index_queue_insert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceinstance',
            name='descriptors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
